### ISSUE TITLE
Idea: upload the source code of the example as artifact

### ISSUE THREAD

**Issue by urish** [SergioGasquez/wokwi-projects#8]
You can use the [upload-artifact](https://github.com/actions/upload-artifact) action to achieve that. 

This way, if there's a code change on Wokwi example, it's easy to see which version a specific CI run picked up. Artifacts are stored for up to 90 days, and they appear at the bottom of the workflow summary page

**Comment by SergioGasquez** [comment]
Thanks for suggesting the idea, just merged #9!
